import { useState } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import Input from '../../components/common/Input';
import Button from '../../components/common/Button';
import ErrorMessage from '../../components/common/ErrorMessage';
import Icon from '../../components/common/Icon';
import Logo from '../../components/layout/Logo';
import { useAuth } from '../../features/auth/auth.context';
import { authErrorMessage } from '../../features/auth/auth.utils';
import { useDocumentTitle } from '../../hooks/useDocumentTitle';
import { useMetaRobots } from '../../hooks/useMetaRobots';
import { passwordProblem } from '../../utils/validation';

/**
 * Only reachable usefully with a valid invite token + its matching email in the query string
 * (generated by an existing admin on /admin/team). Without one, the server rejects the signup
 * outright — this page cannot grant the admin role on its own.
 */
export default function AdminSignup() {
  useDocumentTitle('Create admin account');
  useMetaRobots();
  const { adminSignup } = useAuth();
  const navigate = useNavigate();
  const [params] = useSearchParams();
  const token = params.get('token') || '';
  const email = params.get('email') || '';

  const [form, setForm] = useState({ displayName: '', password: '' });
  const [errors, setErrors] = useState({});
  const [error, setError] = useState('');
  const [submitting, setSubmitting] = useState(false);

  if (!token || !email) {
    return (
      <div className="admin-auth-shell">
        <div className="auth-card admin-auth-card">
          <Logo />
          <div className="notice notice--warning">
            <Icon name="alert" size={18} />
            <p>This page requires a valid invite link from an existing Fixora administrator. Ask them to generate one from the admin team page.</p>
          </div>
          <p className="auth-card__switch">
            <Link to="/admin/login">Back to admin sign in</Link>
          </p>
        </div>
      </div>
    );
  }

  const submit = async (event) => {
    event.preventDefault();
    const next = {};
    if (form.displayName.trim().length < 2) next.displayName = 'Enter your full name';
    const pw = passwordProblem(form.password);
    if (pw) next.password = pw;
    setErrors(next);
    if (Object.keys(next).length) return;

    setSubmitting(true);
    setError('');
    try {
      await adminSignup({ email, password: form.password, displayName: form.displayName.trim(), token });
      navigate('/admin/dashboard', { replace: true });
    } catch (err) {
      setError(authErrorMessage(err));
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="admin-auth-shell">
      <div className="auth-card admin-auth-card">
        <Logo />
        <h1>Create your admin account</h1>
        <p className="muted">Invited as {email}.</p>
        <form className="stack" onSubmit={submit} noValidate>
          <Input label="Full name" autoComplete="name" value={form.displayName} onChange={(e) => setForm({ ...form, displayName: e.target.value })} error={errors.displayName} required />
          <Input label="Email" value={email} disabled hint="Locked to the email this invite was sent to" />
          <Input
            label="Password"
            type="password"
            autoComplete="new-password"
            value={form.password}
            onChange={(e) => setForm({ ...form, password: e.target.value })}
            error={errors.password}
            hint="At least 8 characters with a letter and a number"
            required
          />
          <ErrorMessage error={error} compact />
          <Button type="submit" block size="lg" loading={submitting}>
            Create admin account
          </Button>
        </form>
      </div>
    </div>
  );
}
